/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ytr_jniperformance_JniWrapper */

#ifndef _Included_ytr_jniperformance_JniWrapper
#define _Included_ytr_jniperformance_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ytr_jniperformance_JniWrapper
 * Method:    calculationTask
 * Signature: (I)J
 */
JNIEXPORT jdouble JNICALL Java_ytr_jniperformance_JniWrapper_calculationTask
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
